Feature/products section
KurbatovAS/project5 pull request #1
Opened 2021-09-09 21:00 UTC by SofiaProtsiv

Написано розмітку та стилі для трьох точок 320px, 768px, 1200px
Функціонал Read More ще не реалізований

2021-09-09 22:45 UTC, KurbatovAS requested changes
Ну, ты настоящая умница-красавица. Раньше всех проделала столько работы! Молодчина!

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/utils/_variables.scss
> +$product-card-1: #ffb8ca;
Для этого цвета уже есть переменная: $hero-bg-color
Хотя, как вариант, можно создать уникальную переменную именно для этой карточки, предполагая, что, возможно, нужно будет для этой карточки когда-то цвет изменить не изменяя цвет фона Героя.
Ещё - думаю, это не является важным моментом, но полагаю, что именам переменных для цвета лучше добавлять индекс -color. На пример:  
$product-card-1-color;
$product-card-2-color;
$product-card-3-color; 
Хотя мы манифест классов не делали и не обсуждали стандартизацию переменных, потому, если желаешь, можно оставить твой вариант ;)

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/main.scss
> +@import './base/common';
Если учесть, что в данном конкретном случае в паршале common назначаются свойства для body, то, полагаю, этот паршал по порядку должен идти перед section и container. Быть может я не правильно сделал, что свойства для body поместил в common? Что ты думаешь по этому поводу. 
Я просто переживаю, что бы не было гитконфликта из-за того, что твои изменения для main.scss отличаются от тех, что уже на гите. Как вариант, можем их принять, что бы посмотреть - какая будет в таком случае ситуация. Будет ли конфликт или гит это как-то упорядочит сам, или будет ругаться... :)

2021-09-09 22:45 UTC, KurbatovAS commented on src/partials/products.html
> +<section class="products">
Для секции у нас есть общий класс .section с падингами 100px. 
Тем более в домашках мы как-раз таки использовали общий класс. Думаю, лучше будет всё-же использовать общий класс .section.

2021-09-09 22:45 UTC, KurbatovAS commented on src/partials/products.html
> +        <p class="products__suptitle">100% natural</p>
Вот тут мы дали маху, что не обговорили общие классы для этих заголовков и подзаголовков. На сколько я помню, Григорий говорил, что это у нас подзаголовок секции с классом .section__subtitle
Как вариант, можешь самостоятельно перенести стили для заголовка и подзаголовка в паршал section. Я их приму. Думаю, это нормальная практика.

2021-09-09 22:45 UTC, KurbatovAS commented on src/partials/products.html
> +        <h2 class="products__title">Products</h2>
То-же самое, что и с подзаголовком секции. Полагаю, стоит изменить на .section__title и перенести стили в паршал section.

2021-09-09 22:45 UTC, KurbatovAS commented on src/partials/products.html
> +        <ul class="products__list">
Отсюда (с этого списка) начинается блок product. По крайней мере - мне так же как-то подсказал Григорий :)

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +.products{
По этому поводу я писал выше. Эти стили из .section

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +.products__suptitle{
Это у нас .section__subtitle

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +.products__title{
Это .section__title

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +.products__list{
А тут уже стили для блока  products

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +          margin-bottom: 0;
Попробуй этот margin-bottom: 0; убрать. Думаю, тут должен работать нулевой маржин с таблетки.

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +        @media screen and (min-width: 1200px) {
Подправь точки перелома для десктопа. По ТЗ она у нас 1280px

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +.product-card__span{
Судя по макету - эти точки у нас это svg, но, по идее, можно их сделать и так :)

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +    font-family: DM Sans;
font-family: 'DM Sans' - у нас стоит на body, потому, полагаю, можно тут не писать. Попробуй убрать, проверь, будет ли работать с body.

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +.products__item--icon{
Это, я полагаю, заготовка для стилей svg ?

2021-09-09 22:45 UTC, KurbatovAS commented on src/sass/components/_products.scss
> +    .container {
Ну, и стили на .container я уже, благодаря тебе ;) , добавил в соответственный паршал. Отсюда можно убрать.

2021-09-10 08:41 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +.products{
Змінила на секцію

2021-09-10 08:41 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +.products__suptitle{
Зробила

2021-09-10 08:41 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +.products__title{
Зробила

2021-09-10 08:41 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +.products__list{
Перейменувала

2021-09-10 08:41 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +          margin-bottom: 0;
Видалила лишній марджин

2021-09-10 08:41 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +        @media screen and (min-width: 1200px) {
Змінила (min-width: 1200px) на (min-width: 1280px)

2021-09-10 08:42 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +.product-card__span{
Я пробувала і як псевдоелемент афтер, і свг, але цей мені сподобався найбільше тому залишила

2021-09-10 08:42 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +    font-family: DM Sans;
Видалила. Працює

2021-09-10 08:42 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +.products__item--icon{
Лишнє. Видалила

2021-09-10 08:42 UTC, SofiaProtsiv commented on src/sass/components/_products.scss
> +    .container {
Тут видалила, скопіювала стилі з мейн і додала в __container.scss

2021-09-10 08:42 UTC, SofiaProtsiv commented on src/sass/main.scss
> +@import './base/common';
Змінила так як у мейні ти прописав, скопіювала, конфлікта не має бути
@import './base/normalize';
@import './utils/variables';
@import './base/common';
@import './base/section';
@import './base/container';

2021-09-10 08:42 UTC, SofiaProtsiv commented on src/sass/utils/_variables.scss
> +$product-card-1: #ffb8ca;
змінила на $product-card-№-color

2021-09-10 21:35 UTC, KurbatovAS approved these changes
Поздравляю! Первый Merge pull request в нашем проекте - за тобой! Надеюсь у тебя "легкая рука" ;)

2021-09-10 21:35 UTC, merged

2021-09-12 12:20 UTC, KurbatovAS commented on src/partials/products.html
> +                    <button type="button" class="product-card__button"></button>
Скрылся без вести закрывающий тег </div> 
Не плохо было бы его отыскать и пригвоздить на своей место или разместить объявление о вакантной должности "закрывающего дива" ;D