зробив
KurbatovAS/project5 pull request #15
Opened 2021-09-13 12:01 UTC by konstantin-Ba2mSki

перевірь на баги з 480 до 768 якись трабли

2021-09-13 17:16 UTC, KurbatovAS requested changes

2021-09-13 17:16 UTC, KurbatovAS commented on src/partials/contacts.html
> +<!-- отзывы -->
Думаю, это можно убрать либо изменить на `<!-- контакты -->` :)

2021-09-13 17:16 UTC, KurbatovAS commented on src/partials/contacts.html
> +    <h2 class="visually-hidden">Contacts</h2>
Этот скрытый заголовок красивше было бы сделать/оформить так:
`<h2 class="section__title section__title--visually-hidden">Contacts</h2>`

Но правильно его оформить ты пока, возможно, его не сможешь оформить, потому что у тебя, вероятно, не подтянут пуршл "**_visually-hidden.scss**". Это сделаем позже. Пока всё оставь тут без изменений.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +
Тут получилось так, что это медиа правило никуда не относится: 

@media screen and (min-width: 768px) {
    width: 768px;
    padding-left: 36px;
    padding-right: 36px;
    margin-left: auto;
    margin-right: auto;
    padding: 50px 32px;
К тому-же, тут ещё и потерялись две закрывающие фигурные скобки:
  }
}
Попроси Женю, что бы по своим каналам пробил/объявил в розыск ;D

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +.container--contacts {
У нас есть общий контейнер соследующими свойствами:
.container {
  margin: 0 auto;
  
  @media screen and (min-width: 320px) and (max-width: 767px) {
    min-width: 320px;
    max-width: 480px;
    padding: 0 20px;
  }
  @media screen and (min-width: 768px) {
    width: 768px;
    padding: 0 34px;
  }
  @media screen and (min-width: 1280px) {
    width: 1280px;
    padding: 0 115px;
  }
}

Соответственно, те свойства, что у тебя дублируются,  лучше убрать. По идее, правильнее будет так (но ты проверь, мало ли) :
.container--contacts {
  @media screen and (min-width: 320px) {
    padding: 0 50px;
  }
}

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +
Не хватает двух закрывающих фигурных скобок:
  }
}

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +    width: 320px;
Попробуй убрать эту ширину. Если без неё будет плохо - оставь.
Я дальше по коду посмотрел. У тебя получается в таком случае на "мобилке" контейнер не "резиновый/респонис", а "адаптивный" - размер меняется скачками: 320px, потом "480px". Нужно бы переделать на респонсив. Как вариант, я могу пока принять в виде адаптивки и слить в мейн, а потом ты создашь ветку "**bugfix/название-бага**" и там исправишь этот момент.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +    .contacts__item:not(:last-child) {
Этот весь кусок кода: 

.contacts__item:not(:last-child) {
      margin-bottom: 20px;
    }
  }
  @media screen and (min-width: 480px) {
    width: 480px;
    .contacts__item:not(:last-child) {
      margin-bottom: 20px;
    }
  }

  @media screen and (min-width: 768px) {
    width: 768px;
    padding-left: 36px;
    padding-right: 36px;
    margin-left: auto;
    margin-right: auto;
    padding: 50px 32px;  _**- эти паддинги не корректно ставить в класс ":not(:last-child)", потому как они будут относится ко всем элементам списка, кроме последнего, а тебе этого не нужно. Для этого лучше создать отдельный класс ".contacts__item" и туда назначить эти падинги либо, по SASS-у покажу ниже как  лучше сделать.**_

К тому же я ещё внизу нашел не законченное оформление для "**.contacts**" и начатое оформление "**.contacts__item**" - ты их там, дальше, удали и пропиши тут всё как я напишу. 
Конечно-же проверь, всё ли будет правильно работать, мало ли, может где-то я и ошибся. 


.contacts__item {
  padding: 43px 20px;

  @media screen and (min-width: 768px) {
    flex-basis: calc((100% - 6 * 10px) / 3);
    margin: 10px;
    padding: 50px 32px;
  }
  @media screen and (min-width: 1280px) {
    flex-basis: calc((100% - 6 * 15px) / 3);
    margin: 15px;
    padding: 60px 43px;
  }

  &:not(:last-child) {
    @media screen and (max-width: 767px) {
      margin-bottom: 20px;
    }
    @media screen and (min-width: 480px) and (max-width: 767px) {
      width: 480px;
    }
  }
}

А вот тебе оформление для "**.contacts**" :
.contacts {
  @media screen and (min-width: 768px) {
    display: flex;
    margin: -10px;
  }
  @media screen and (min-width: 1280px) {
    margin: -15px;
  }
}

Только ты их размести выше стилей "**.contacts__item**"

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      display: flex;
Вариант выравнивания с флексом правильный, но ещё можно было сделать без флекса, а просто паддингами, но это, думаю, не критично.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      width: 73px;
Помню, Григорий рекомендовал кнопкам не задавать жёсткие размеры, что бы не вышло случайно, что изменённый контент вылез за границы. Он рекомендовал прописывать размеры через:
min-width: 73px;
Высоту вообще рекомендовал не задавать. Попробуй так сделать.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      width: 138px;
Так же и тут попробуй с размерами поэкспериментировать

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      width: 157px;
Я ниже нашел снова стили для этого-же класса "**.schedule**"

Возьми те что ниже удали, а эти (свои) замени этим кодом:

.schedule {
  width: 173px;
  padding-bottom: 25px;
  border-top: 1px solid $main-line-color;
  border-bottom: 1px solid $main-line-color;

  @media screen and (min-width: 768px) {
    width: 157px;
    padding-bottom: 30px;
  }
  @media screen and (min-width: 1280px) {
    width: 234px;
    padding-bottom: 32px;
  }
}

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      margin: 0;
Возможно этот маржин лишний. Попробуй без него.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +    .schedule__item.schedule__item—day {
.schedule__item.schedule__item—day - такой каскад классов нужен для скрипта?
Если нет, то тогда правильнее это всё оформить так:
.schedule__item {
  font-weight: 500;
  font-size: 14px;
  line-height: 1.86;
}

.schedule__item—day {
  padding-top: 25px;
  color: $main-text-color;
}

.schedule__item—time {
   color: $section-subtitle-color;
}
**Заметь, что общие стили для текста я вынес в общий класс "_.schedule__item_", а те стили, что уникальны - в отдельных классах-модификаторах. Так правильнее.** 

А если использовать возможности SASS, то можно так:
.schedule__item {
  font-weight: 500;
  font-size: 14px;
  line-height: 1.86;

  &—day {
    padding-top: 25px;
    color: $main-text-color;
  }
  &—time {
    color: $section-subtitle-color;
  }
}
Но такой вариант усложняет чтение кода, потому не рекомендуется ;)

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      width: 192px;
То-же самое на счёт размеров кнопок. Можешь попробовать как я выше писал.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      width: 192px;
То-же самое на счёт размеров кнопок. Можешь попробовать как я выше писал.

2021-09-13 17:16 UTC, KurbatovAS commented on src/partials/contacts.html
> +      <button type="button" class="button">
Класс по БЭМ-у правильнее назначить такой "**buttons__locations**". Лучше исправь и в scss стилях тоже.

2021-09-13 17:16 UTC, KurbatovAS commented on src/partials/contacts.html
> +      <button type="button" class="button button__franchise">
Такой класс `class="button button__franchise"` не корректно писать. Если ты выше исправишь класс для кнопки "Our Locations" на "**buttons__locations**", то уже не выйдет такой каскад классов. 
Лучше сделать просто два раздельных класса для кнопок:
**buttons__locations**
и
**buttons__franchise**
И стили для каждой из них назначать, хоть это и не красиво так как идентичные стили будут дублироваться, что увеличит общий объем кода. Красивее было бы создать класс-плейсхолдер, к примеру"**%buttons**" (хотя такое имя заведомо - стрёмное из-за того, что может уже кем-то использовано), куда помещаются идентичные стили, а в раздельные классы **button__locations** и **button__franchise** добавить только те стили, что отличаются. Если хочешь, можешь заморочиться и так сделать. Для пример, можешь посмотреть - так сделан класс "**visually-hidden**"

2021-09-13 17:16 UTC, KurbatovAS commented on src/partials/contacts.html
> +    <div class="buttons">
Вообще, так класс называть довольно стрёмно, так как такое же имя класса могут 100-500 раз захотеть написать другие разработчики и будет "Ой, а почему это оно не так как надо отображается?" :)
Лучше придумывать что-то более уникальное, лучше - относящееся к твоей секции.

2021-09-13 17:16 UTC, KurbatovAS commented on src/partials/contacts.html
> +        <svg class="logo-locations" width="5" height="8">
Тут имя класса лучше так-же по БЭМ-у назначить по принципу "**имя-блока__имя-элемента**":
к примеру: "**buttons__icon**"

2021-09-13 17:16 UTC, KurbatovAS commented on src/partials/contacts.html
> +        <svg class="logo-franchise" width="5" height="8">
Этой иконке задай такой же класс ""**buttons__icon**"". Там разница в пару пикселей роли не сыграет, а лишних пару строк кода в стилях уберёшь и облегчишь загрузку сайта ;)

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +    .button {
На счёт классов для кнопок я уже написал в html файле

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +      margin-right: 15px;
У тебя же уже выше открыт класс "**.button**"
Перенеси этот **margin-right: 15px;**

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +    .contacts {
Логичнее и удобнее для чтения разместить стили для блока "**.contacts**" выше, посел стилей для контейнера. Там где ты уже назначал стили для "**.contacts__item:not(:last-child)**".
К тому же тут ты уже делаешь сеткой, назначая всему списку минусовый маржин: "**margin: -15px;**". Только это нужно назначать медиа правилом, начиная с "теблетки". На мобилке, ведь, сеткой не нужно делать. Помню, Григорий возмущался на "сетку" в "мобилке". В мобилке достаточно нижний марджин для "нот ласт чайлд". 
Короче, я тебе выше написал код, как должно быть.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +    .schedule {
У тебя уже есть это класс выше на 82 строке с этими параметрами:
.schedule {
      padding-bottom: 30px;
      border-top: 1px solid $main-line-color;
      border-bottom: 1px solid $main-line-color;
      width: 157px;

Убери эти.

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +.contacts__cafe {
У тебя с этой строки идёт копия стилей тех, что сверху или это мне кажется?

2021-09-13 17:16 UTC, KurbatovAS commented on src/sass/components/_contacts.scss
> +
Возьми весь этот код, что я ниже написал, удали, потому что что:
1. "**.contacts**" - я тебе выше написал
2. "**.contacts__item**" - я тебе выше написал
3. "**.buttons**" - я тебе ниже напишу
4. медиаправило в этом месте, как мне кажется, ничего полезного не делает. Я его правильно выше написал
5. "**.schedule**" - я тебе выше написал
.contacts {
   display: flex;
      margin: -15px;
    }

    .contacts__item {
      flex-basis: calc((100% - 5 * 15px) / 3);
      margin: 15px;
    }

    .buttons {
      margin-top: 81px;
    }
  }

  @media screen and (min-width: 1280px) {
    width: 1280px;
    padding: 52px 43px;

    .schedule {
      padding-bottom: 32px;
      border-top: 1px solid $main-line-color;
      border-bottom: 1px solid $main-line-color;
      width: 234px;
    }
  }
}

Вот тебе правильный код для "**.buttons**":
.buttons {
  margin-top: 55px;

  @media screen and (min-width: 768px) {
    margin-top: 80px;
  }
  @media screen and (min-width: 1280px) {
    margin-top: 85px;
  }
}

2021-09-14 07:13 UTC, konstantin-Ba2mSki commented on src/partials/contacts.html
> +<!-- отзывы -->
+

2021-09-14 07:13 UTC, konstantin-Ba2mSki commented on src/partials/contacts.html
> +<!-- отзывы -->
виправив

2021-09-14 15:58 UTC, closed without merging