сделала разметку, набросала основные стили
KurbatovAS/project5 pull request #2
Opened 2021-09-09 22:51 UTC by NataliyaKulibaba

У меня остались вопросы:
 1. скрипт
 2. в мобильном меню как делаем полоски - сделала как бордер топ и ботом, но они не на всю ширину секции, но можно костылями исправить (градиентом не уверена, т.к. много подбирать и может сломаться)
 3. кружочки справа - поставила как бэкграунд - но слетают либо на десктопе, либо на таблетки. та же ситуация с поинтами (циферками справа)
 4. в ТЗ указано что все картинки - абсолют, но, мне кажется, более уместным бэкграундом мороженко и элипс. Сделала так.
 5. вопрос с картинками, я так понимаю, еще открыт (как все-таки правильно прописывать путь). С точками у меня все ломается.
 6. не доделала кружочек внизу типа Рид Мор

2021-09-10 08:08 UTC, KurbatovAS requested changes
1. скрипт - пока в наличии нет. Григория ещё раз дерну поэтому вопросу.
2. полоски мобильного меню - пока ответить не могу (нужно больше времени что бы разобраться - нужно уехать). Можно вопрос в группу задать. 
3. блок с кружочками и циферками, наверное, можно сделать отдельным div-ом (ещё не смотрел как ты сделал, может так и есть) в котором будет p-шка с цифрами и кружочки бекграундом
4. Да, твой вариант, как по мне, хорош. Посмотрим как оно будет. Если ломаться ничего не будет - то СУПЕР
5. с картинками - будем пробовать
6. ещё есть время ;)

2021-09-10 08:08 UTC, KurbatovAS commented on src/images/images-hero/Burger.svg
> +<svg width="20" height="14" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 1h20M0 7h20M0 13h20" stroke="#D41443"/></svg>
Пока пусть svg-хи будут отдельными файлами, но потом их нужно будет удалить, когда добавим спрайт.

2021-09-10 08:08 UTC, KurbatovAS commented on src/partials/hero-header.html
> +    <img class="logo" src="/images/images-hero/logo.png" alt="Логотип">
Можно попробовать залить картинки без точки в начале пути. Если Гит всё-же не будет их юзать без точки, то будем разбираться.

2021-09-10 08:08 UTC, KurbatovAS commented on src/partials/hero-header.html
> +        <use class="icon-menu" href="/sprite-hero.svg#icon-Burger" width="20px" height="12px"></use>
Если мы используем дефис в качестве разделителя между слов в названиях файлов (картинок, символов (symbol) внутри спрайта, и прочих файлов), то тогда лучше заглавные буквы не использовать, а делать все маленькие: "icon-burger".

2021-09-10 08:08 UTC, KurbatovAS commented on src/partials/hero-header.html
> +        <use href="/sprite-hero.svg#icon-biggest" width="6px" height="8px"></use>
Без того, что бы попробовать на живой странице в инспекторе кода, однозначно сказать пока не могу, нужно ли точно в use добавлять размеры иконки ( width="6px" height="8px"). Думаю, достаточно будет размеров внутри тега svg. Проверь этот момент и если без размеров внутри use будут размеры ОК, то убери из use.

2021-09-10 08:08 UTC, KurbatovAS commented on src/partials/hero-header.html
> +        <use class="menu-toggle__cross" href="/sprite-hero.svg#icon-close"></use>
Класс .menu-toggle__cross ты, вроде-бы, нигде не используешь. Если не планируешь использовать, лучше убрать.

2021-09-10 10:34 UTC, NataliyaKulibaba commented on src/partials/hero-header.html
> +        <use class="icon-menu" href="/sprite-hero.svg#icon-Burger" width="20px" height="12px"></use>
+

2021-09-10 10:37 UTC, NataliyaKulibaba commented on src/partials/hero-header.html
> +        <use href="/sprite-hero.svg#icon-biggest" width="6px" height="8px"></use>
исправила

2021-09-10 10:38 UTC, NataliyaKulibaba commented on src/partials/hero-header.html
> +        <use class="menu-toggle__cross" href="/sprite-hero.svg#icon-close"></use>
done

2021-09-11 00:23 UTC, KurbatovAS requested changes

2021-09-11 00:23 UTC, KurbatovAS commented on src/partials/hero-header.html
> +      <p class="hero__points hero__points--first">16 <span class=" hero-points__description">cafes</span></p>
Не уверен, что это важно, но тем не менее - убери пробел перед именем класса " hero-points__description". Может из-за него оно ломается при растягивании.

2021-09-11 00:23 UTC, KurbatovAS commented on src/sass/main.css
> +@charset "UTF-8";
Что-то мне не нравится, что происходят напрямую изменения в main.css

2021-09-11 00:23 UTC, KurbatovAS commented on src/sass/main.css.map
> +{
Так же и тут не должно быть, мне кажется, - в main.css.map

2021-09-11 10:49 UTC, closed without merging