доделала по макету, не считая ИД и скриптов
KurbatovAS/project5 pull request #8
Opened 2021-09-11 19:55 UTC by NataliyaKulibaba

внизу после тега хедер есть разметка для бэкдропа и стили для него в scss, не хватает скриптов и надежды что он заработает

2021-09-11 20:13 UTC, KurbatovAS requested changes

2021-09-11 20:13 UTC, KurbatovAS commented on src/partials/hero-header.html
> +    <p class="modal__title">Оставьте свои данные, мы вам перезвоним</p>
У нас макет на английском, по идее все тексты должны быть английские. Хотя сделали нам основную разметку с "<html lang="ru">"

2021-09-13 13:59 UTC, SofiaProtsiv submitted a review, later dismissed

2021-09-13 14:59 UTC, SofiaProtsiv submitted a review, later dismissed

2021-09-13 17:46 UTC, KurbatovAS approved these changes, later dismissed

2021-09-13 17:46 UTC, KurbatovAS commented on src/images/sprite.svg
> +<symbol id="right_sarrow" viewBox="0 0 32 32">
Может стоит имя иконке дать более лаконичное, чем "right_**s**arrow" :) или я чего-то недопонял ?

2021-09-13 17:46 UTC, KurbatovAS commented on src/partials/hero-header.html
> +  <div class="container container__page-header">
Если делать как ты говорила (по БЭМ-у), то, наверное, правильнее будет не "container__page-header", а "page-header__container" - если мы подразумеваем этот класс как микс. Или я всё-же не прав?

2021-09-13 17:49 UTC, KurbatovAS approved these changes

2021-09-13 19:27 UTC, closed without merging